import type { Metadata } from "next";
import fixelDisplay from "@/fonts/fixelDisplay";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fixelDisplay.className}>
        <div className="flex flex-col justify-between items-center min-h-screen pt-4 bg-white">
          <div className="relative ">
            <div className="sticky top-4 left-0 right-0 z-100">
            <Header />
            </div>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
